server:
  port: 58086
spring:
  application:
    name: ms-report
  datasource:
    url: jdbc:postgresql://${MILITARY_DISTRICT_MS_REPORT_DB_URL}
    username: ${MILITARY_DISTRICT_MS_REPORT_DB_USER}
    password: ${MILITARY_DISTRICT_MS_REPORT_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${MILITARY_DISTRICT_MS_REPORT_OAUTH2_CERT_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.jdbc.core: TRACE