version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: military-district-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 15432:5432
    volumes:
      - military-district-db-data-dev:/var/lib/postgresql/data
    networks:
      - military-district-net-dev
  cache:
    image: redis:7.2.4-alpine3.19
    container_name: military-district-cache-dev
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 16379:6379
    volumes:
      - military-district-cache-data-dev:/data
    networks:
      - military-district-net-dev
  pgadmin:
    image: dpage/pgadmin4
    container_name: military-district-pgadmin-dev
    restart: always
    ports:
      - 18888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - military-district-pgadmin-data-dev:/var/lib/pgadmin
      - ./pgadmin/servers-dev.json:/pgadmin4/servers.json
    networks:
      - military-district-net-dev
    depends_on:
      db:
        condition: service_healthy
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: military-district-rediscommander
    restart: always
    environment:
      - REDIS_HOSTS=military-district:military-district-cache-dev:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 16380:8081
    networks:
      - military-district-net-dev
    depends_on:
      cache:
        condition: service_healthy
volumes:
  military-district-db-data-dev:
  military-district-cache-data-dev:
  military-district-pgadmin-data-dev:
networks:
  military-district-net-dev: