{
 "title": "Apollo Router Metrics",
 "description": "Apollo GraphQL Router.",
 "tags": [
  "apollo graphql",
  "apollo router",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apollo_router_span_count{kind=\"busy\", span=\"supergraph\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Busy Supergraph"
    },
    {
     "expr": "apollo_router_span_count{kind=\"duration\", span=\"execution\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Execution Duration"
    },
    {
     "expr": "apollo_router_span_count{kind=\"duration\", span=\"query_planning\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Query Planning Duration"
    },
    {
     "expr": "apollo_router_span_count{kind=\"duration\", span=\"request\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Request Duration"
    },
    {
     "expr": "apollo_router_span_count{kind=\"duration\", span=\"subgraph\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Subgraph Duration"
    },
    {
     "expr": "apollo_router_span_count{kind=\"duration\", span=\"supergraph\", otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Supergraph Duration"
    }
   ]
  },
  {
   "title": "HTTP Request Counters",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "apollo_router_http_requests_total{status=\"200\",subgraph=\"ms-military\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "MS Military Requests"
    },
    {
     "expr": "apollo_router_http_requests_total{status=\"200\",subgraph=\"ms-formation\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "MS Formation Requests"
    },
    {
     "expr": "apollo_router_http_requests_total{status=\"200\",subgraph=\"ms-infrastructure\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "MS Infrastructure Requests"
    },
    {
     "expr": "apollo_router_http_requests_total{status=\"200\",subgraph=\"ms-equipment\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "MS Equipment Requests"
    },
    {
     "expr": "apollo_router_http_requests_total{status=\"200\",subgraph=\"ms-weapon\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "MS Weapon Requests"
    }
   ]
  },
  {
   "title": "Cache Counters",
   "type": "stat",
   "gridPos": { "x": 16, "y": 8, "w": 8, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apollo_router_cache_hit_count_total{kind=\"query planner\",storage=\"memory\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "apollo_router_cache_miss_count_total{kind=\"query planner\",storage=\"memory\",otel_scope_name=\"apollo/router\"}",
     "legendFormat": "Cache Misses"
    }
   ]
  }
 ]
}