spring:
  application:
    name: military-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:15432/db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        cache:
          redisson:
            config: redisson-dev.yml
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    user: user
    password: password
    url: jdbc:postgresql://localhost:15432/db
  graphql:
    graphiql:
      enabled: true
server:
  port: 18081
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
logging:
  level:
    org.springframework.cache: TRACE
graphql:
  datetime:
    scalars:
      date:
        format: yyyy-MM-dd